version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: admin_user
      MINIO_ROOT_PASSWORD: admin_pass
    command: server --console-address ":9090" /data

#volumes:
#  minio_storage:

#  postgres:
#    container_name: postgres-db
#    image: postgres:14.0-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_HOST=postgres
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    ports:
#      - ${POSTGRES_PORT}:${POSTGRES_PORT}
#  app:
#    container_name: olp
##    image: mirabdulloh/olp
#    build:
#      context: ./
#    depends_on:
#      - postgres
#      - minio
#    restart: unless-stopped
#    ports:
#      - ${PORT}:${API_LOCAL_PORT}
#    environment:
#      - PORT=${PORT}
#      - API_LOCAL_PORT=${API_LOCAL_PORT}
#      - API_HOST=${API_HOST}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#      - POSTGRES_PORT=${POSTGRES_PORT}
#      - POSTGRES_LOCAL_PORT=${POSTGRES_LOCAL_PORT}
#      - POSTGRES_HOST=postgres
#      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
#      - ACCESS_TOKEN_TIME=${ACCESS_TOKEN_TIME}
#      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
#      - REFRESH_TOKEN_TIME=${REFRESH_TOKEN_TIME}
#      - PRIVATE_KEY=${PRIVATE_KEY}
#      - EXPIRES_TIME=${EXPIRES_TIME}
volumes:
#  pgdata:
  minio_storage: